[workspace]

members = [
    "crates/db-address-space",
    "crates/db-allocator",
    "crates/db-arch",
    "crates/db-boot",
    "crates/db-device",
]

[patch.crates-io]
db-boot = { path = "crates/db-boot" }
